version: '3.7'

services:
  # Apache Server
  webserver:
    image: php:7.4-apache
    container_name: packet-apache
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - mynetwork
    depends_on:
      - mailhog
    links:
      - mailhog
    working_dir: /var/www/html 

  # MailHog Email Service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mynetwork

networks:
  mynetwork:
