version: '3.7'

services:
  # Apache Server
  webserver:
    image: php:7.4-apache
    container_name: packet-apache
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - mynetwork

  # Mailu Email Service
  mailu:
    image: mailu/mailu:latest
    container_name: email-service
    ports:
      - "587:587"
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - DOMAINNAME=example.com
    networks:
      - mynetwork

networks:
  mynetwork:
